#!/usr/bin/env php
<?php
declare(strict_types = 1);

use Slothsoft\Unity\DotNet\FormatLog;
use Slothsoft\Core\DOMHelper;

array_shift($_SERVER['argv']);
$_SERVER['argc'] --;

$_composer_autoload_path ??= __DIR__ . '/../vendor/autoload.php';
include $_composer_autoload_path;

const HELP = <<<'EOT'
Transforms a dotnet format JSON log to a JUnit tests XML. Returns the generated XML.
    
Usage:
composer exec transform-dotnet-format "path/to/format-report.json"

EOT;

if ($_SERVER['argc'] < 1) {
    echo HELP;
    return;
}

$args = $_SERVER['argv'];

$jsonPath = array_shift($args);

$log = new FormatLog($jsonPath);

$document = $log->asDocument();

$dom = new DOMHelper();
$document = $dom->transformToDocument($document, 'farah://slothsoft@unity/xsl/to-junit');

$document->formatOutput = true;
$document->save('php://output');