#!/usr/bin/env php
<?php
declare(strict_types = 1);

use Slothsoft\Unity\Command\ApplicationFactory;

$_composer_autoload_path ??= __DIR__ . '/../vendor/autoload.php';
include $_composer_autoload_path;

exit(ApplicationFactory::create()->run());
