#!/usr/bin/env php
<?php
declare(strict_types = 1);

use Slothsoft\Farah\FarahUrl\FarahUrl;
use Slothsoft\Farah\FarahUrl\FarahUrlArguments;
use Slothsoft\Unity\UnityProjectInfo;

array_shift($_SERVER['argv']);
$_SERVER['argc'] --;

include $_composer_autoload_path ?? __DIR__ . '/../vendor/autoload.php';

if ($_SERVER['argc'] < 2) {
    echo <<<'EOT'
    Run a specific method inside a Unity project.
        
    Usage:
    composer exec unity-method "path/to/project" "Method.To.Execute" ["additional params", ...]
            
    EOT;
    return;
}

$args = $_SERVER['argv'];

$workspace = array_shift($args);
$method = array_shift($args);

$project = UnityProjectInfo::create($workspace);

if (! $project) {
    throw new InvalidArgumentException("Failed to find a Unity project at '$workspace'!");
}

$url = FarahUrl::createFromComponents('slothsoft@unity', '/project/method', FarahUrlArguments::createFromValueList([
    'workspace' => $project->path,
    'method' => $method,
    'args' => $args
]));

readfile((string) $url);
