#!/usr/bin/env php
<?php
declare(strict_types = 1);

use Slothsoft\Farah\FarahUrl\FarahUrl;
use Slothsoft\Farah\FarahUrl\FarahUrlArguments;

array_shift($_SERVER['argv']);
$_SERVER['argc'] --;

include $_composer_autoload_path ?? __DIR__ . '/../vendor/autoload.php';

if ($_SERVER['argc'] < 3) {
    echo <<<'EOT'
    Run all tests inside a Unity project.
        
    Usage:
    composer exec unity-tests "path/to/project" "path/to/results.xml" [EditMode|PlayMode|Platform]+
            
    EOT;
    return;
}

$args = $_SERVER['argv'];

$workspace = array_shift($args);
$resultsFile = array_shift($args);
$modes = $args;

$url = FarahUrl::createFromComponents('slothsoft@unity', '/project/tests-junit', FarahUrlArguments::createFromValueList([
    'workspace' => $workspace,
    'modes' => $modes
]));

$resultsDirectory = dirname($resultsFile);
if (! is_dir($resultsDirectory)) {
    mkdir($resultsDirectory, 0777, true);
}

copy((string) $url, $resultsFile);

if (!is_file($resultsFile)) {
    exit(1);
}