#!/usr/bin/env php
<?php
declare(strict_types = 1);

use Slothsoft\Farah\FarahUrl\FarahUrl;
use Slothsoft\Farah\FarahUrl\FarahUrlArguments;
use Slothsoft\Farah\Module\Module;

array_shift($_SERVER['argv']);
$_SERVER['argc'] --;

$_composer_autoload_path ??= __DIR__ . '/../vendor/autoload.php';
include $_composer_autoload_path;

const HELP = <<<'EOT'
Get one of the project settings of a Unity project.
    
Usage:
composer exec unity-project-setting "path/to/project" "setting-name"

EOT;

if ($_SERVER['argc'] < 2) {
    echo HELP;
    return;
}

$args = $_SERVER['argv'];

$workspace = array_shift($args);
$name = array_shift($args);

$url = FarahUrl::createFromComponents('slothsoft@unity', '/project/setting', FarahUrlArguments::createFromValueList([
    'workspace' => $workspace,
    'name' => $name
]));

$document = Module::resolveToDOMWriter($url)->toDocument();

echo $document->textContent;