#!/usr/bin/env php
<?php
declare(strict_types = 1);

use Slothsoft\Farah\FarahUrl\FarahUrl;

array_shift($_SERVER['argv']);
$_SERVER['argc'] --;

$_composer_autoload_path ??= __DIR__ . '/../vendor/autoload.php';
include $_composer_autoload_path;

const HELP = <<<'EOT'
Shortcut for calling "unityhub help". Can be used to verify that your Unity Hub installation was succesully located.
    
Usage:
composer exec unity-help

EOT;

if ($_SERVER['argc'] > 0) {
    echo HELP;
    return;
}

$url = FarahUrl::createFromComponents('slothsoft@unity', '/hub/help');

readfile((string) $url);