#!/usr/bin/env php
<?php
declare(strict_types = 1);

use Slothsoft\Unity\DaemonClient;

array_shift($_SERVER['argv']);
$_SERVER['argc'] --;

include $_composer_autoload_path ?? __DIR__ . '/../vendor/autoload.php';

$daemon = new DaemonClient(5050);
foreach ($daemon->call('help') as $response) {
    echo $response;
}