services:
  web:
    user: root
    platform: linux/amd64
    build:
      platforms:
        - linux/amd64
    environment:
        - UNITY_CREDENTIALS_USR
        - UNITY_CREDENTIALS_PSW
        - EMAIL_CREDENTIALS_USR
        - EMAIL_CREDENTIALS_PSW
        - UNITY_NO_GRAPHICS=1
    volumes:
        - unity-binaries:/root/Unity

volumes:
    unity-binaries:
        external: true
