services:
  web:
    environment:
        - GITHUB_PAT
        - JENKINS_PAT
    volumes:
      - ${DDEV_APPROOT}:${DDEV_APPROOT}
      - ~/acp/.codex/:/home/${DDEV_USER}/.codex/
      - ~/acp/.claude/:/home/${DDEV_USER}/.claude/
      - ~/acp/.claude.json:/home/${DDEV_USER}/.claude.json
      - ~/acp/.config/:/home/${DDEV_USER}/.config/
