services:
  web:
    environment:
        - UNITY_CREDENTIALS_USR
        - UNITY_CREDENTIALS_PSW
        - EMAIL_CREDENTIALS_USR
        - EMAIL_CREDENTIALS_PSW
        - UNITY_NO_GRAPHICS=1
    volumes:
        - ~/Unity:/home/${DDEV_USER}/Unity
